Rabbitmq
elemntorBootkamp/storge-actions pull request #28
Opened 2023-06-26 10:21 UTC by chayaZalaznik

2023-06-27 23:04 UTC, chanakamin requested changes

2023-06-27 23:04 UTC, chanakamin commented on rabbitMQ/send_message.js
> +    console.warn(err);
remove console

2023-06-27 23:04 UTC, chanakamin commented on rabbitMQ/send_message.js
> +    console.log(' [x] Sent \'%s\'', message);
console...

2023-06-27 23:04 UTC, chanakamin commented on rabbitMQ/ReceivingMessage.js
> +export const startConsumer = async () => {
where this method is called?

2023-06-27 23:04 UTC, chanakamin commented on rabbitMQ/ReceivingMessage.js
> +  const queueName = 'website-subscriptions';
save this value in a config file, and use it from there, here and in send_message file.

2023-06-27 23:04 UTC, chanakamin commented on rabbitMQ/ReceivingMessage.js
> +  const functionName = data.extraParam;
please, don't move the "functionName"
instead, you can send an "action"
its more clear. the name of the action and the function shouldn't be the same.

2023-06-28 09:50 UTC, chayaZalaznik commented on app.js
> +const port = 3000;
לא קשור עלינו זה שינוי קודם 
סתם שיניתי לו מיקום....

2023-06-28 09:52 UTC, cheina1588 requested changes

2023-06-29 06:30 UTC, tamargit1 approved these changes

2023-06-29 06:33 UTC, tamargit1 approved these changes

2023-06-29 06:41 UTC, tamargit1 approved these changes

2023-06-29 06:42 UTC, tamargit1 approved these changes

2023-06-29 06:46 UTC, tamargit1 approved these changes

2023-06-29 11:47 UTC, cheina1588 approved these changes

2023-06-29 16:56 UTC, merged